### ISSUE TITLE
Tracking issue for variants

### ISSUE THREAD

**Issue by JaniM** [JaniM/variant-go-server#6]
These are some of the variants people have mentioned so far

- [X] one color go
- [ ] blind go
- [x] hidden move go
- [X] 4+1
- [X] tetris go
- [X] toroidal go
- [ ] magnet go (I forget the rule)
- [ ] phantom go (you don't see opponents' stones)
- [x] pixel go (you place 2x2 blobs)
- [ ] simultaneous turns
- [ ] quantum go
- [x] lottery go / traitor go (you have a chance to place the opponent's stone instead)
- [ ] Keima go: https://senseis.xmp.net/?KeimaGo
- [x] Zen go
- [ ] Atari atari go (you can't capture stones if the precending player put a group in atari)
- [ ] Stone swap (player can choose to swap two adjacent stones instead of placing a new one)
- [ ] Random placement after a move (play -> get a position picked randomly -> place another stone there if legal)

**Comment by Arttaaz** [comment]
simultaneous turns might be the hardest one to do, since it involves real time play. I don't really know if it's gonna be that fun for go too. There is a shogi game on the switch that is in real time, but each piece have a cooldown after being used, and the cooldown change depending on the piece you use. I'm not sure you could translate that well to go.

**Comment by Arttaaz** [comment]
Oh I just found the post talking about it being moves at the same time instead of real time, okay forget what I said!

**Comment by JaniM** [comment]
Added one color go, because it's really quick to do now that I have a proper view model.
