### ISSUE TITLE
Tracking issue for new mobile client

### ISSUE THREAD

**Issue by JaniM** [JaniM/variant-go-server#75]
Currently known missing features for feature parity with the old client:
- [ ] Game view
  - [ ] Hidden move go setup phase
  - [ ] Timer display
  - [ ] Move history
  - [ ] Rule listing
- [ ] Game creation options
  - [ ] Timer options in game creation
  - [ ] Board size selection
- [ ] Sounds (stone placement, clock warnings)
- [ ] Error indicators
- [ ] SGF export

Currently known issues:
- [ ] Can't scroll all the way down in game listing
- [ ] Toroidal go is beyond broken

Wanted new features:
- [ ] Easy targeting with touch
